### ISSUE TITLE
Filters and card issue

### ISSUE THREAD

**Issue by marcomele98** [christiancagnazzo/se2022-02-HikeTracking#43]
Hi, your application is very nice but according to what we said today I would prefer as a hiker to have a button on the Hike page to reset the filters without having to go to the filters page.
Another small change to make the application even more beautiful could be to make all the hike cards the same size.

**Comment by christiancagnazzo** [comment]
Thanks! We have resolved the issue
https://github.com/christiancagnazzo/se2022-02-HikeTracking/commit/38dfee25b17d47b07e4e760981151fefe98cc1fd
